import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/lib/providers";
import { Toaster } from "@/components/ui/sonner";
import { Layout } from "@/components";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Base64",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Layout>{children}</Layout>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
